package com.fisherwiki.core.infer

/**
 * Image preprocessing, shared by the phone and by the desktop test suite.
 *
 * **Why this is its own class and not three lines inside the classifier.**
 * Preprocessing is the single most common source of silent accuracy loss in a
 * deployed vision model. Training resizes with one interpolation, one crop
 * convention, one channel order and one normalisation; if serving differs in
 * any of them, accuracy drops without any error being raised anywhere. So the
 * exact recipe lives here, is described precisely below, and is pinned by
 * `PreprocessorParityTest` against reference tensors generated by the Python
 * training pipeline.
 *
 * The recipe, in order:
 *
 * 1. **EXIF orientation is applied by the caller before we see pixels.** Phone
 *    cameras store landscape sensor data plus a rotation tag; training images
 *    were decoded with orientation applied, so serving must match.
 * 2. **Resize the short edge to [ResizeSpec.resizeTo]** preserving aspect ratio,
 *    using bilinear interpolation with `align_corners=false` semantics - the
 *    same convention as torchvision's `Resize` on PIL images.
 * 3. **Centre-crop to `size x size`.** For a fish photographed by an angler the
 *    subject is nearly always central; a random or corner crop at inference
 *    would just discard the fish.
 * 4. **Convert to float in 0..1**, RGB order (not BGR).
 * 5. **Normalise per channel**: `(x - mean) / std`, with mean/std carried in the
 *    pack manifest rather than hard-coded, so a model trained with different
 *    statistics cannot be mispaired with the wrong constants.
 * 6. **Emit NCHW float32**, which is what the exported ONNX graph expects.
 */
object Preprocessor {

    /**
     * Resize geometry.
     *
     * [resizeTo] is the short-edge target before cropping. Training uses
     * `resize(256) -> centreCrop(224)`, i.e. a ratio of 256/224 = 1.142, which
     * keeps a small margin so the crop does not clip a fish that fills the
     * frame. The ratio is derived from [cropTo] rather than fixed so that a
     * pack using a different input size stays consistent.
     */
    data class ResizeSpec(val cropTo: Int, val resizeRatio: Float = 256f / 224f) {
        val resizeTo: Int get() = Math.round(cropTo * resizeRatio)
    }

    /**
     * Turn ARGB pixels into a normalised NCHW float tensor.
     *
     * @param pixels packed `0xAARRGGBB`, row-major, length `width * height`.
     *   This is exactly what `Bitmap.getPixels` gives on Android and
     *   `BufferedImage.getRGB` gives on the JVM, so no platform type leaks in.
     * @param mean per-channel mean in RGB order, on a 0..1 scale.
     * @param std per-channel standard deviation in RGB order.
     * @return float array of length `3 * size * size` in NCHW order.
     */
    fun toTensor(
        pixels: IntArray,
        width: Int,
        height: Int,
        size: Int,
        mean: FloatArray,
        std: FloatArray,
        resizeRatio: Float = 256f / 224f,
    ): FloatArray {
        require(width > 0 && height > 0) { "empty image ${width}x${height}" }
        require(pixels.size >= width * height) {
            "pixel buffer holds ${pixels.size}, need ${width * height}"
        }
        require(mean.size == 3 && std.size == 3) { "mean/std must be per-RGB-channel" }
        require(std.all { kotlin.math.abs(it) > 1e-6f }) { "std contains zero" }

        val spec = ResizeSpec(size, resizeRatio)
        val target = spec.resizeTo

        // Scale so the SHORT edge lands on `target`, preserving aspect ratio.
        val scale = target.toDouble() / minOf(width, height).toDouble()
        val scaledW = maxOf(1, Math.round(width * scale).toInt())
        val scaledH = maxOf(1, Math.round(height * scale).toInt())

        // Centre crop window, expressed in the scaled image's coordinates.
        val cropX = (scaledW - size) / 2
        val cropY = (scaledH - size) / 2

        // Separable triangle-filter resample with support scaled by the
        // downscale factor, i.e. antialiased. Only the cropped output window is
        // computed, so nothing outside the crop is resampled.
        val hx = Weights.build(width, scaledW, cropX, size)
        val hy = Weights.build(height, scaledH, cropY, size)

        val out = FloatArray(3 * size * size)
        val plane = size * size

        // Horizontal pass: (height) x (size) intermediate, per channel.
        val tmp = FloatArray(3 * height * size)
        for (y in 0 until height) {
            val rowIn = y * width
            val rowOut = y * size
            for (ox in 0 until size) {
                val start = hx.starts[ox]
                val n = hx.counts[ox]
                val wbase = ox * hx.maxTaps
                var accR = 0f
                var accG = 0f
                var accB = 0f
                for (k in 0 until n) {
                    val px = pixels[rowIn + (start + k)]
                    val wgt = hx.weights[wbase + k]
                    accR += ((px shr 16) and 0xFF) * wgt
                    accG += ((px shr 8) and 0xFF) * wgt
                    accB += (px and 0xFF) * wgt
                }
                tmp[0 * height * size + rowOut + ox] = accR
                tmp[1 * height * size + rowOut + ox] = accG
                tmp[2 * height * size + rowOut + ox] = accB
            }
        }

        // Vertical pass, straight into the normalised output.
        for (c in 0 until 3) {
            val cBase = c * height * size
            val m = mean[c]
            val s = std[c]
            for (oy in 0 until size) {
                val start = hy.starts[oy]
                val n = hy.counts[oy]
                val wbase = oy * hy.maxTaps
                val dstRow = c * plane + oy * size
                for (ox in 0 until size) {
                    var acc = 0f
                    for (k in 0 until n) {
                        acc += tmp[cBase + (start + k) * size + ox] * hy.weights[wbase + k]
                    }
                    out[dstRow + ox] = (acc / 255f - m) / s
                }
            }
        }
        return out
    }

    /**
     * Precomputed resampling weights for one axis.
     *
     * **Why a filtered resample and not plain bilinear.**
     * The first implementation sampled two taps per axis. That is correct for
     * *upscaling* and wrong for downscaling: going from 500 px to 256 px, a
     * 2-tap read skips most of the source pixels entirely, which aliases. PIL -
     * and therefore the training pipeline - scales the filter support by the
     * downscale factor so every source pixel contributes, which is what
     * "antialias" means in `torchvision.transforms.Resize`.
     *
     * `PreprocessorParityTest` caught the difference: peak disagreement against
     * the Python reference was 0.617 in normalised units (~36 grey levels) at
     * high-contrast edges, while the RMS stayed small — the signature of
     * aliasing rather than a structural error. Training on antialiased images
     * and serving aliased ones is exactly the silent train/serve skew this
     * class exists to prevent.
     */
    private class Weights(
        val starts: IntArray,
        val counts: IntArray,
        val weights: FloatArray,
        val maxTaps: Int,
    ) {
        companion object {
            /**
             * @param srcSize source extent
             * @param dstSize full resized extent (before cropping)
             * @param cropStart first output index we actually need
             * @param outCount how many output samples to produce
             */
            fun build(srcSize: Int, dstSize: Int, cropStart: Int, outCount: Int): Weights {
                val scale = dstSize.toDouble() / srcSize.toDouble()
                // Filter support: 1.0 when upscaling, widened when downscaling.
                val support = if (scale < 1.0) 1.0 / scale else 1.0
                val maxTaps = (Math.ceil(support * 2.0).toInt() + 2).coerceAtLeast(2)

                val starts = IntArray(outCount)
                val counts = IntArray(outCount)
                val weights = FloatArray(outCount * maxTaps)

                for (i in 0 until outCount) {
                    val d = i + cropStart
                    // Centre of this output sample in source coordinates.
                    val centre = (d + 0.5) / scale
                    var lo = Math.floor(centre - support).toInt()
                    var hi = Math.ceil(centre + support).toInt()
                    if (lo < 0) lo = 0
                    if (hi > srcSize) hi = srcSize
                    if (hi <= lo) {
                        lo = centre.toInt().coerceIn(0, srcSize - 1)
                        hi = lo + 1
                    }
                    var n = hi - lo
                    if (n > maxTaps) {
                        // Only possible from rounding at the extreme edges.
                        n = maxTaps
                        hi = lo + n
                    }

                    var total = 0.0
                    val base = i * maxTaps
                    for (k in 0 until n) {
                        // Triangle (bilinear) kernel, normalised to the support.
                        val x = ((lo + k) + 0.5 - centre) / support
                        val w = if (x <= -1.0 || x >= 1.0) 0.0 else 1.0 - Math.abs(x)
                        weights[base + k] = w.toFloat()
                        total += w
                    }
                    if (total <= 0.0) {
                        // Degenerate: fall back to nearest so the row is not blank.
                        for (k in 0 until n) weights[base + k] = 0f
                        weights[base] = 1f
                    } else {
                        val inv = (1.0 / total).toFloat()
                        for (k in 0 until n) weights[base + k] *= inv
                    }
                    starts[i] = lo
                    counts[i] = n
                }
                return Weights(starts, counts, weights, maxTaps)
            }
        }
    }

    /**
     * Crop geometry for a detector-supplied box, expanded by [padFraction].
     *
     * A tight fish box usually clips fins, which are diagnostic; padding first
     * and then letting [toTensor] centre-crop recovers them. The box is clamped
     * to the image, and a degenerate box falls back to the whole frame rather
     * than producing an empty tensor.
     */
    fun expandBox(
        x0: Int, y0: Int, x1: Int, y1: Int,
        width: Int, height: Int,
        padFraction: Float = 0.12f,
    ): IntArray {
        val bw = x1 - x0
        val bh = y1 - y0
        if (bw <= 1 || bh <= 1) return intArrayOf(0, 0, width, height)
        val padX = Math.round(bw * padFraction)
        val padY = Math.round(bh * padFraction)
        val nx0 = (x0 - padX).coerceIn(0, width - 1)
        val ny0 = (y0 - padY).coerceIn(0, height - 1)
        val nx1 = (x1 + padX).coerceIn(nx0 + 1, width)
        val ny1 = (y1 + padY).coerceIn(ny0 + 1, height)
        return intArrayOf(nx0, ny0, nx1, ny1)
    }

    /** Extract a sub-rectangle of ARGB pixels, for use after [expandBox]. */
    fun cropPixels(
        pixels: IntArray, width: Int, height: Int,
        x0: Int, y0: Int, x1: Int, y1: Int,
    ): Triple<IntArray, Int, Int> {
        val cw = (x1 - x0).coerceAtLeast(1)
        val ch = (y1 - y0).coerceAtLeast(1)
        val out = IntArray(cw * ch)
        for (y in 0 until ch) {
            val sy = (y0 + y).coerceIn(0, height - 1)
            System.arraycopy(pixels, sy * width + x0.coerceIn(0, width - 1), out, y * cw,
                minOf(cw, width - x0.coerceIn(0, width - 1)))
        }
        return Triple(out, cw, ch)
    }
}
